### PREPROCESSING

libs for preprocessing

In [19]:
import numpy as np
import pandas as pd
import json

Tracks may lack lyrics inherently (e.g., instrumentals), not due to retrieval issues. These tracks will be included in the analysis.

In [20]:
df = pd.read_csv('df_tracks.csv')
df.head()

,id,track_id,dsp,lyrics,created_at,updated_at,track_id-2,source,title,main_artist,artists,genre,album,year,duration_ms,storage_uri,created_at-2,updated_at-2
0,1150,3687638,"{""key"": 4, ""mode"": 1, ""tempo"": 125.12210083007...",NaN,2026-03-20 17:51:29.828508,2026-03-20 17:51:29.828296,3687638,yandex_music,Something Here In My Heart (Keeps A-Tellin' Me...,Paper Dolls,Paper Dolls,pop,Catch the Wind: Evocative 60s Pop,NaN,179320,/app/storage/3687638.mp3,2026-03-20 13:37:43.044894,2026-03-20 17:51:11.330511
1,131,4462120,"{""key"": null, ""mode"": 1, ""tempo"": 129.05625915...",NaN,2026-03-20 09:06:36.746773,2026-03-20 09:06:36.74641,4462120,yandex_music,Nel Blu Dipinto Di Blu (Volare),Domenico Modugno,Domenico Modugno,estrada,Giovane Amore,2013.0,216500,/app/storage/4462120.mp3,2026-03-20 09:06:13.563677,2026-03-20 09:06:13.562963
2,18,148137770,"{""key"": 9, ""mode"": 0, ""tempo"": 150.11441040039...",NaN,2026-03-20 08:30:28.157316,2026-03-20 08:30:28.156996,148137770,yandex_music,G-Woman,ICEGERGERT,ICEGERGERT,rusrap,Глаз Бога,2026.0,140800,/app/storage/148137770.mp3,2026-03-20 08:30:12.797335,2026-03-20 08:30:12.796638
3,3,147727731,"{""key"": null, ""mode"": 0, ""tempo"": 120.02976989...","Тону, тону.. Я в глазах твоих тону Чем ты даль...",2026-03-20 08:26:11.23555,2026-03-20 08:30:59.743026,147727731,yandex_music,Тону,HOLLYFLAME,HOLLYFLAME,ruspop,Тону,2026.0,163000,/app/storage/147727731.mp3,2026-03-20 08:25:54.356936,2026-03-20 08:25:54.356115
4,6,143821827,"{""key"": 2, ""mode"": 0, ""tempo"": 99.488456726074...",Запах кожи и валюта на диване Даже если попрош...,2026-03-20 08:27:02.212688,2026-03-20 08:31:15.424902,143821827,yandex_music,БАНК,ICEGERGERT,ICEGERGERT,rusrap,БАНК,2025.0,177750,/app/storage/143821827.mp3,2026-03-20 08:26:43.867316,2026-03-20 08:26:43.866561

In [21]:
df.tail()

,id,track_id,dsp,lyrics,created_at,updated_at,track_id-2,source,title,main_artist,artists,genre,album,year,duration_ms,storage_uri,created_at-2,updated_at-2
2876,2877,707386,"{""key"": null, ""mode"": 1, ""tempo"": 129.98948669...","Check, check, check, check Set the time for th...",2026-03-21 06:47:10.377138,2026-03-21 06:47:10.376964,707386,yandex_music,Breathe,The Prodigy,The Prodigy,breakbeatgenre,The Fat of the Land - Expanded Edition,1997.0,334050,/app/storage/707386.mp3,2026-03-21 06:46:34.405065,2026-03-21 06:46:34.404394
2877,2878,137670,"{""key"": 0, ""mode"": 0, ""tempo"": 161.51232910156...",As I walk through the valley of the shadow of ...,2026-03-21 06:47:38.00658,2026-03-21 06:47:38.006378,137670,yandex_music,Gangsta's Paradise,Coolio,Coolio,rap,Gangsta's Paradise,1995.0,241010,/app/storage/137670.mp3,2026-03-21 06:47:11.510962,2026-03-21 06:47:11.509847
2878,2879,1206206,"{""key"": 1, ""mode"": 0, ""tempo"": 94.477691650390...","One, two, three and to the fo' Snoop Doggy Dog...",2026-03-21 06:48:05.030778,2026-03-21 06:48:05.030603,1206206,yandex_music,Nuthin' But A 'G' Thang,Snoop Dogg,Snoop Dogg,foreignrap,"Me & My Homies, Vol. 1",NaN,235180,/app/storage/1206206.mp3,2026-03-21 06:47:40.24072,2026-03-21 06:47:40.239784
2879,2880,10216,"{""key"": 0, ""mode"": 1, ""tempo"": 151.49057006835...",I follow the Moskva and down to Gorky Park Lis...,2026-03-21 06:48:40.750099,2026-03-21 06:48:40.749925,10216,yandex_music,Wind Of Change,Scorpions,Scorpions,hardrock,Crazy World,1990.0,311240,/app/storage/10216.mp3,2026-03-21 06:48:06.262042,2026-03-21 06:48:06.261012
2880,2881,631620,"{""key"": null, ""mode"": 1, ""tempo"": 114.65684509...",Everybody dance now! Everybody dance now! Give...,2026-03-21 06:49:07.94959,2026-03-21 06:49:07.949415,631620,yandex_music,Gonna Make You Sweat (Everybody Dance Now),C+C Music Factory,C+C Music Factory,soundtrack,Evan Almighty,2007.0,243690,/app/storage/631620.mp3,2026-03-21 06:48:41.803633,2026-03-21 06:48:41.802629

In [22]:
df = df.drop(['source', 'track_id-2', 'created_at', 'updated_at', 'created_at-2', 'updated_at-2', 'storage_uri'], axis = 1)
df.head()

,id,track_id,dsp,lyrics,title,main_artist,artists,genre,album,year,duration_ms
0,1150,3687638,"{""key"": 4, ""mode"": 1, ""tempo"": 125.12210083007...",NaN,Something Here In My Heart (Keeps A-Tellin' Me...,Paper Dolls,Paper Dolls,pop,Catch the Wind: Evocative 60s Pop,NaN,179320
1,131,4462120,"{""key"": null, ""mode"": 1, ""tempo"": 129.05625915...",NaN,Nel Blu Dipinto Di Blu (Volare),Domenico Modugno,Domenico Modugno,estrada,Giovane Amore,2013.0,216500
2,18,148137770,"{""key"": 9, ""mode"": 0, ""tempo"": 150.11441040039...",NaN,G-Woman,ICEGERGERT,ICEGERGERT,rusrap,Глаз Бога,2026.0,140800
3,3,147727731,"{""key"": null, ""mode"": 0, ""tempo"": 120.02976989...","Тону, тону.. Я в глазах твоих тону Чем ты даль...",Тону,HOLLYFLAME,HOLLYFLAME,ruspop,Тону,2026.0,163000
4,6,143821827,"{""key"": 2, ""mode"": 0, ""tempo"": 99.488456726074...",Запах кожи и валюта на диване Даже если попрош...,БАНК,ICEGERGERT,ICEGERGERT,rusrap,БАНК,2025.0,177750

In [23]:
df['dsp'][0]

'{"key": 4, "mode": 1, "tempo": 125.12210083007812, "energy": 0.9272043704986572, "valence": 0.4940676689147949, "loudness": -15.041776657104492, "duration_ms": 179320, "speechiness": 0.9366663098335266, "acousticness": 0.2643619775772095, "danceability": 0.268546462059021, "instrumentalness": 0.06688044965267181}'

In [24]:
df_analysis = pd.json_normalize(df['dsp'].apply(json.loads))
df_analysis = df_analysis.drop(['key', 'duration_ms'], axis = 1)
df = pd.concat([df.drop('dsp', axis=1), df_analysis], axis=1)
df.head()

,id,track_id,lyrics,title,main_artist,artists,genre,album,year,duration_ms,mode,tempo,energy,valence,loudness,speechiness,acousticness,danceability,instrumentalness
0,1150,3687638,NaN,Something Here In My Heart (Keeps A-Tellin' Me...,Paper Dolls,Paper Dolls,pop,Catch the Wind: Evocative 60s Pop,NaN,179320,1,125.122101,0.927204,0.494068,-15.041777,0.936666,0.264362,0.268546,0.066880
1,131,4462120,NaN,Nel Blu Dipinto Di Blu (Volare),Domenico Modugno,Domenico Modugno,estrada,Giovane Amore,2013.0,216500,1,129.056259,0.144913,0.014602,-20.943279,0.820610,0.947892,0.097830,0.315972
2,18,148137770,NaN,G-Woman,ICEGERGERT,ICEGERGERT,rusrap,Глаз Бога,2026.0,140800,0,150.114410,0.902406,0.607868,-9.952200,0.930681,0.117253,0.868400,0.125951
3,3,147727731,"Тону, тону.. Я в глазах твоих тону Чем ты даль...",Тону,HOLLYFLAME,HOLLYFLAME,ruspop,Тону,2026.0,163000,0,120.029770,0.943165,0.378489,-9.149795,0.984062,0.164663,0.813531,0.031680
4,6,143821827,Запах кожи и валюта на диване Даже если попрош...,БАНК,ICEGERGERT,ICEGERGERT,rusrap,БАНК,2025.0,177750,0,99.488457,0.967640,0.545020,-8.822800,0.897843,0.064915,0.954115,0.092136

In [29]:
df.to_csv('processed_tracks.csv', index=False)